language: java
jdk:
  - openjdk11 # java8이면, openjdk8

branches:
  only:
    - master # git default 브런치를 등록한다. (ex. master)

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
     - chmod +x gradlew

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - kakao1302@naver.com

######################## 새롭게 추가한 코드 ##########################

before_deploy:
  - mkdir -p before-deploy #zip에 포함시킬 파일들을 담을 디렉토리
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.war before-deploy/
  - cd before-deploy && zip -r before-deploy * #before-deploy 폴더로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy #상위 디렉토리로 이동 후 deploy 폴더 생성
  - mv before-deploy/before-deploy.zip deploy/freelec-springboot2-webservice.zip #deploy로 zip 파일
#  - zip -r spring_deploy_test *
#  - mkdir -p deploy
#  - mv spring_deploy_test.zip deploy/spring_deploy_test.zip

deploy:
  # S3로 파일업로드
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repos settings에 설정된 값
    bucket: jongjin97-spring-build # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true # master말고 다른 모든 브런치 허용
      
   # aws codedeploy
  - provider: codedeploy
    access_key_id : $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jongjin97-spring-build # s3 버킷
    key: spring_deploy_test.zip  # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: shop-deploy # aws 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: shop-group # aws 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
   
###############################################################
